version: '3.8'

services:
  # Meta-Controller API (Port 8000)
  meta-controller:
    build:
      context: ../services/
      dockerfile: Dockerfile.meta_controller
    ports:
      - "8000:8000"
    container_name: meta-controller
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/dissonance_db
    depends_on:
      - postgres

  # Proposer Service (Port 8001)
  proposer:
    build:
      context: ../models/
      dockerfile: Dockerfile.proposer
    ports:
      - "8001:8001"
    container_name: proposer

  # Critic Service (Port 8002)
  critic:
    build:
      context: ../critic/
      dockerfile: Dockerfile.critic
    ports:
      - "8002:8002"
    container_name: critic

  # Learner Service (Port 8003)
  learner:
    build:
      context: ../learner/
    ports:
      - "8003:8003"
    container_name: learner

  # Safety Gate Service (Port 8004)
  safety-gate:
    build:
      context: ../safety_gate/
    ports:
      - "8004:8004"
    container_name: safety-gate

  # Evaluator Service (persistent orchestration loop)
  evaluator:
    build:
      context: ../evaluator/
    container_name: evaluator
    environment:
      - META_CONTROLLER_API_URL=http://meta-controller:8000
      - PROPOSER_API_URL=http://proposer:8001
      - CRITIC_API_URL=http://critic:8002
      - LEARNER_API_URL=http://learner:8003
      - SAFETY_GATE_API_URL=http://safety-gate:8004
    depends_on:
      - meta-controller
      - proposer
      - critic
      - learner
      - safety-gate

  # PostgreSQL Database for Metadata Store
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dissonance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MinIO for S3-compatible Object Storage
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: