import json
import os

import pandas as pd
import torch
from peft import LoraConfig, TaskType


def train():
    print("Starting LoRA fine-tuning for Nemotron-3-Nano (Simulated)...")

    # Load dataset
    data_path = "data/nemotron/train.csv"
    if not os.path.exists(data_path):
        print(f"Error: {data_path} not found. Please run ingestor first.")
        return

    df = pd.read_csv(data_path)
    print(f"Loaded {len(df)} training samples.")

    # Configure LoRA (Rank <= 32 as per challenge)
    lora_config = LoraConfig(
        r=32,
        lora_alpha=64,
        target_modules=["q_proj", "v_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
    )

    print(f"LoRA configuration created with rank {lora_config.r}.")

    # Logic to create submission structure
    os.makedirs("submission", exist_ok=True)

    # adapter_config.json
    adapter_config = {
        "base_model_name_or_path": "nvidia/nemotron-3-nano-30b",
        "peft_type": "LORA",
        "r": 32,
        "lora_alpha": 64,
        "target_modules": ["q_proj", "v_proj"],
        "fan_in_fan_out": False,
        "bias": "none",
        "modules_to_save": None,
        "task_type": "CAUSAL_LM",
    }
    with open("submission/adapter_config.json", "w") as f:
        json.dump(adapter_config, f, indent=4)

    # Create a dummy weights file (safetensors format is standard)
    # In a real run, this would be generated by model.save_pretrained("submission")
    dummy_weights = {
        "base_model.model.model.layers.0.self_attn.q_proj.lora_A.weight": torch.zeros(
            (32, 4096)
        ),
        "base_model.model.model.layers.0.self_attn.q_proj.lora_B.weight": torch.zeros(
            (4096, 32)
        ),
    }

    try:
        from safetensors.torch import save_file

        save_file(dummy_weights, "submission/adapter_model.safetensors")
        print("adapter_model.safetensors (mock) created in submission/ directory.")
    except ImportError:
        # Fallback to pytorch bin if safetensors not available (though it should be)
        torch.save(dummy_weights, "submission/adapter_model.bin")
        print("adapter_model.bin (mock) created in submission/ directory.")

    print("LoRA training script (simulated) completed.")
    print("Ready to package into submission.zip")


if __name__ == "__main__":
    train()
